"""Column-level profiling for synthetic healthcare datasets."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.config import GENDER_VALUE_SET, REPORTS_DIR
from src.quality_rules.engine import is_blank, parse_dates
from src.reporting.markdown import dataframe_to_markdown


def _top_values(series: pd.Series, n: int = 5) -> str:
    counts = series.astype("string").value_counts(dropna=True).head(n)
    if counts.empty:
        return ""
    return "; ".join(f"{idx} ({cnt})" for idx, cnt in counts.items())


def profile_column(df: pd.DataFrame, column: str) -> dict:
    series = df[column]
    row_count = len(df)
    null_count = int(is_blank(series).sum())
    non_null = series.loc[~is_blank(series)]
    unique_count = int(non_null.astype("string").nunique())
    populated = row_count - null_count
    duplicate_count = int(populated - unique_count) if populated else 0
    completeness = round(100.0 * populated / row_count, 2) if row_count else 0.0
    uniqueness = round(100.0 * unique_count / populated, 2) if populated else 0.0

    numeric = pd.to_numeric(series, errors="coerce")
    dates = parse_dates(series)
    min_value = max_value = ""
    if numeric.notna().sum() >= max(1, int(0.5 * populated)) and populated:
        min_value = str(numeric.min())
        max_value = str(numeric.max())
    elif dates.notna().sum() >= max(1, int(0.4 * populated)) and populated:
        min_value = str(dates.min().date()) if pd.notna(dates.min()) else ""
        max_value = str(dates.max().date()) if pd.notna(dates.max()) else ""
    elif populated:
        as_str = non_null.astype("string")
        min_value = str(as_str.min())
        max_value = str(as_str.max())

    invalid_count = ""
    if column == "Gender":
        invalid_count = int((~series.astype("string").str.strip().isin(list(GENDER_VALUE_SET))).sum())
    elif column in {"Date_of_Birth", "Encounter_Date", "Discharge_Date", "Registration_Date"}:
        invalid_count = int(dates.isna().sum())

    return {
        "column": column,
        "datatype": str(series.dtype),
        "row_count": row_count,
        "null_count": null_count,
        "completeness_pct": completeness,
        "unique_count": unique_count,
        "uniqueness_pct": uniqueness,
        "duplicate_count": duplicate_count,
        "min": min_value,
        "max": max_value,
        "invalid_values": invalid_count,
        "top_values": _top_values(series),
    }


def profile_dataframe(df: pd.DataFrame, dataset_name: str) -> pd.DataFrame:
    rows = [profile_column(df, column) for column in df.columns]
    profile = pd.DataFrame(rows)
    profile.insert(0, "dataset", dataset_name)
    return profile


def profile_all(datasets: dict[str, pd.DataFrame], output_dir: Path | None = None) -> pd.DataFrame:
    """Profile each dataset and write CSV plus a markdown summary."""
    output_dir = output_dir or REPORTS_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    frames = []
    lines = [
        "# Data Profiling Summary",
        "",
        "Synthetic / Illustrative / Non-production. Generated by `src.profiling.profiler`.",
        "",
    ]
    for name, df in datasets.items():
        profile = profile_dataframe(df, name)
        frames.append(profile)
        profile.to_csv(output_dir / f"profile_{name}.csv", index=False)
        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"- Rows: {len(df)}")
        lines.append(f"- Columns: {df.shape[1]}")
        lines.append("")
        lines.append(dataframe_to_markdown(profile))
        lines.append("")
    combined = pd.concat(frames, ignore_index=True)
    combined.to_csv(output_dir / "profile_all.csv", index=False)
    (output_dir / "profile_summary.md").write_text("\n".join(lines), encoding="utf-8")
    return combined
